server:
  port: 8081

spring:
  application:
    name: catalog
    
hystrix:
  command:
    default:    # command Key. use 'default' for global setting.
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500       
      metrics: #1분(60000)동안 최소 1회 호출 이상, 50% 이상 실패면 circuit open
        rollingStats: 
          timeInMilliseconds: 60000     
      circuitBreaker:
        requestVolumeThreshold: 1 
        errorThresholdPercentage: 50

            
#customer:
#  ribbon:
#    listOfServers: localhost:8082, localhost:8083    
eureka:
#  instance:
#    서비스의 호스트 이름이 아닌 IP 주소를 Eureka Server 에 등록하도록 지정 (디폴트 false)
#    기본적으로 유레카는 호스트 이름으로 접속하는 서비스를 등록하는데 DNS 가 지원된 호스트 이름을 할당하는 서버 기반 환경에서는 잘 동작하지만, 컨테이너 기반의 배포에서 컨테이너는 DNS 엔트리가 없는 임의의 생성된 호스트 이름을 부여받아 시작하므로 컨테이너 기반 배포에서는 해당 설정값을 false 로 하는 경우 호스트 이름 위치를 정상적으로 얻지 못함
#    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/